version: '3'
services:
  db:
    container_name: cdb_database
    image: postgres
    volumes:
      - sample_db:/var/lib/postgresql/data
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=cdb
      - POSTGRES_USER=cdb_usr
      - POSTGRES_PASSWORD=cdb_pwd
      - PGDATA=/var/lib/postgresql/data/pgdata

  back:
    build: back/prod/.
    ports:
      - "8080:8080"
    depends_on:
      - db
    links:
      - "db:database"
volumes:
  sample_db: {}
